services:
  kuma:
    image: louislam/uptime-kuma:1
    container_name: libertai-kuma
    restart: always
    ports:
      - "8082:3001"
    volumes:
      - uptime_kuma_data:/app/data

  monitoring:
    build:
      dockerfile: ./Dockerfile
    image: libertai-monitoring
    container_name: libertai-monitoring
    restart: always
    ports:
      - "8081:8000"
    env_file:
      - .env

volumes:
  uptime_kuma_data:
